# Generated by Django 5.2.7 on 2025-10-13 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='boost_recuso',
            field=models.TextField(default=10, max_length=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='counter',
            name='boton',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='counter',
            name='num_recurso',
            field=models.TextField(default=10, max_length=70),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='counter',
            name='nombre',
            field=models.CharField(max_length=70),
        ),
    ]
